### ISSUE TITLE
links on welcome (index.php)

### ISSUE THREAD

**Issue by cambro** [cosmolab/chemdb#10]
Before diving into this... the welcome page is loading fine, but all links on the homepage/welcome throw 404s. The links are all of the form ```/index.php/projects```.

Question: are these links supposed to be of the form ```/index.php/quartz_chem```? If not, any idea why they are incorrect? Perhaps a path variable someplace? I'm quite confident that a connection to a DB is not being established on index.php load, as the db/username/password can be correct or wrong in the config/database.php and it doesn't affect index.php behavior at all.

Thanks for entertaining a simple mechanical question. I've forked repo at UW-Macrostrat and am tweaking there before submitting a pull for your consideration.

**Comment by zploskey** [comment]
Have you set the base_url in `app/config/config.php`? I believe those those links are generated using what is set there.

**Comment by zploskey** [comment]
The landing page does not access the database, so you will need to access another page to test your database settings.

**Comment by cambro** [comment]
The base_url is set fine, at least as indicated by the fact that index.php is displaying styling and linked images correctly (if I change the base_url then the styling and images break).

What should the URL be for "Projects" and "Manage Projects"? Presently they are ```/index.php/projects```

**Comment by zploskey** [comment]
The correct link depends on your setting of `$config['base_url']`, but on my local setup with base_url set to `http://localhost/chemdb/` the project links go to `http://localhost/chemdb/index.php/projects`. Can you share your setting for base_url and the complete URL of the links that are not working?

**Comment by cambro** [comment]
That is identical to my current set up. I have same base_url and the same links are shown. However, a 404 is returned.

**Comment by zploskey** [comment]
I can't seem to reproduce this issue, so I either don't have enough information about how to reproduce it or it's some problem with how you have set up your development environment.

What operating system, web server and PHP versions are you running?

When you're shown a 404 the browser navigation bar shows you are at `http://localhost/chemdb/index.php/projects`? Is this a 404 from the application (our has some styling) or a 404 from your web server? If this were a database configuration error I would not expect you to get a 404, more likely an exception from our database library.

Permissions all look OK for files under app/, particularly app/views and app/controllers and their contents, to be read by the web server?

The only thing I can think of that might otherwise be an issue is the URI protocol setting. You might try setting `$config['uri_protocol'] = 'QUERY_STRING';` in app/config/config.php.

Here is the troubleshooting section of the CodeIgniter documentation on which this application is based which may be helpful: https://www.codeigniter.com/user_guide/installation/troubleshooting.html

**Comment by cambro** [comment]
```$config['index_page'] = 'index.php?';```
this did it

**Comment by zploskey** [comment]
Awesome. This is not necessary when running on Apache, which is what all of our installs use that I am aware of. If that is what you would use in production you probably will only need to add the ? while doing development in your current setup.

**Comment by cambro** [comment]
Now on to configuring doctrine to use unix socket connections (I don't think this configuration is accounted for in the ```$db['default']``` options in /config/database.php).

**Comment by zploskey** [comment]
I think the appropriate way to use a socket connection is to set your hostname to `unix(/path/to/socket)`, based on http://doctrine1.readthedocs.io/en/latest/en/manual/introduction-to-connections.html. The DSN string being built there is the PEAR style, see http://pear.php.net/manual/en/package.database.db.intro-dsn.php.

**Comment by cambro** [comment]
Yes, that is correct!
But it turns out that it wasn't necessary. A shortcut was had and the standard mysql connection worked.

FYI, ```mysqli``` as dbdriver in /config/database.php threw this error:
```Message: Couldn't locate driver named mysqli```
Doesn't make any sense as mysqli is listed as a valid driver. But, in any case, I simplified to mysql and let php.ini handle the socket and it was all good.

**Comment by zploskey** [comment]
Yeah some of the documentation in that code is not correct as it's a holdover from the CodeIgniter database documentation, while we switched to using Doctrine a long time ago. Doctrine just calls it mysql. I'll look into improving the comments there.

**Comment by cambro** [comment]
But what I don't get is that both are described as supported here:
http://doctrine.readthedocs.io/en/latest/en/manual/introduction-to-connections.html

Not worth worrying too much about though...

**Comment by zploskey** [comment]
Doctrine 1 is unsupported these days and I expect to migrate to something else eventually. To my knowledge mysqli never worked, but if you set it to mysql it uses the mysql driver for PDO, so it's not the old PHP mysql driver.
